services:
  app:
    image: chama_o_samu:prod
    working_dir: /var/www/html
    ports:
      - 8069:80
      - 8068:443
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    volumes:
      - ./:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./logs/integrado.log:/var/www/html/storage/logs/integrado.log
      - ./logs/laravel.log:/var/www/html/storage/logs/laravel.log
      - ./logs/custom.log:/var/www/html/storage/logs/custom.log
      - ./logs/apache_access.log:/var/log/apache2/access.log
      - ./logs/apache_error.log:/var/log/apache2/error.log
    networks:
      - chama_o_samu_ssl
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - DATABASE_URL=postgres://user:password@postgres:5432/chama_o_samu_db
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs/postgres.log:/var/lib/postgresql/data/log/postgresql.log
      - ./start_postgres.sh:/var/lib/postgresql/data/start_postgres.sh
    networks:
      - chama_o_samu_ssl
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chama_o_samu_db
      - TZ=America/Sao_Paulo
    command: "/bin/sh /var/lib/postgresql/data/start_postgres.sh"

networks:
  chama_o_samu_ssl:
    driver: overlay

volumes:
  postgres_data:
