services:
  app:
    image: chama_o_samu:prod
    working_dir: /var/www/html
    ports:
      - 8069:80
      - 8068:443
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: on-failure
    volumes:
      - ./:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - chama_o_samu_ssl
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    healthcheck:
      test: ["CMD-SHELL", "curl -I -f http://localhost || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3

networks:
  chama_o_samu_ssl:
    driver: overlay
